# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drones.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64rones.proto\x12\x06\x44rones\"\x07\n\x05\x45mpty\"\x1c\n\x0cRegistration\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x0eRegistrationId\x12\n\n\x02id\x18\x01 \x01(\x05\"/\n\x08Waypoint\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\"A\n\x08Position\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x02\x32\xb1\x01\n\x07Greeter\x12:\n\x08register\x12\x14.Drones.Registration\x1a\x16.Drones.RegistrationId\"\x00\x12\x32\n\rsend_position\x12\x10.Drones.Position\x1a\r.Drones.Empty\"\x00\x12\x36\n\x0flisten_waypoint\x12\r.Drones.Empty\x1a\x10.Drones.Waypoint\"\x00\x30\x01\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_REGISTRATION = DESCRIPTOR.message_types_by_name['Registration']
_REGISTRATIONID = DESCRIPTOR.message_types_by_name['RegistrationId']
_WAYPOINT = DESCRIPTOR.message_types_by_name['Waypoint']
_POSITION = DESCRIPTOR.message_types_by_name['Position']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'drones_pb2'
  # @@protoc_insertion_point(class_scope:Drones.Empty)
  })
_sym_db.RegisterMessage(Empty)

Registration = _reflection.GeneratedProtocolMessageType('Registration', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATION,
  '__module__' : 'drones_pb2'
  # @@protoc_insertion_point(class_scope:Drones.Registration)
  })
_sym_db.RegisterMessage(Registration)

RegistrationId = _reflection.GeneratedProtocolMessageType('RegistrationId', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATIONID,
  '__module__' : 'drones_pb2'
  # @@protoc_insertion_point(class_scope:Drones.RegistrationId)
  })
_sym_db.RegisterMessage(RegistrationId)

Waypoint = _reflection.GeneratedProtocolMessageType('Waypoint', (_message.Message,), {
  'DESCRIPTOR' : _WAYPOINT,
  '__module__' : 'drones_pb2'
  # @@protoc_insertion_point(class_scope:Drones.Waypoint)
  })
_sym_db.RegisterMessage(Waypoint)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'drones_pb2'
  # @@protoc_insertion_point(class_scope:Drones.Position)
  })
_sym_db.RegisterMessage(Position)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=24
  _EMPTY._serialized_end=31
  _REGISTRATION._serialized_start=33
  _REGISTRATION._serialized_end=61
  _REGISTRATIONID._serialized_start=63
  _REGISTRATIONID._serialized_end=91
  _WAYPOINT._serialized_start=93
  _WAYPOINT._serialized_end=140
  _POSITION._serialized_start=142
  _POSITION._serialized_end=207
  _GREETER._serialized_start=210
  _GREETER._serialized_end=387
# @@protoc_insertion_point(module_scope)
